export const kpis = [
  {
    id: 'ota',
    label: 'OTA',
    tag: { text: 'Below SLA', tone: 'error' },
    value: '93.0%',
    valueTone: 'error',
    deltaIcon: 'arrow_downward',
    deltaTone: 'error',
    delta: '2.0pp',
    deltaNote: 'vs 95% SLA',
    footLabel: 'Owner',
    footValue: 'Vendor',
    drilldown: true,
  },
  {
    id: 'avg-delay',
    label: 'Avg Delay',
    tag: { text: 'Active', tone: 'neutral' },
    value: '1.1',
    valueUnit: 'min',
    deltaIcon: 'arrow_upward',
    deltaTone: 'error',
    delta: '0.3 min',
    deltaNote: 'Prior cycle',
    footLabel: 'Primary',
    footValue: 'Traffic',
  },
  {
    id: 'no-show',
    label: 'No-show',
    tag: { text: 'Variance', tone: 'warning' },
    value: '2.8%',
    deltaIcon: 'arrow_upward',
    deltaTone: 'warning',
    delta: '0.7pp',
    deltaNote: 'Peer 2.3%',
    footLabel: 'Owner',
    footValue: 'Office',
  },
  {
    id: 'cost',
    label: 'Cost / Trip',
    tag: { text: 'Audit', tone: 'neutral' },
    value: '\u20B91,394',
    deltaIcon: 'arrow_upward',
    deltaTone: 'error',
    delta: '8.2%',
    deltaNote: 'Peer \u20B91,236',
    footLabel: 'Owner',
    footValue: 'Ops',
  },
  {
    id: 'safety',
    label: 'Safety Sev-1',
    tag: { text: 'Critical', tone: 'error-solid', pulse: true },
    value: '18',
    valueUnit: 'Open',
    valueTone: 'error',
    footLabel: 'Owner',
    footValue: 'Ops Desk',
    footTone: 'error',
    safety: true,
  },
  {
    id: 'csat',
    label: 'CSAT',
    tag: { text: 'Stable', tone: 'success' },
    value: '4.82',
    valueUnit: '/5',
    deltaNote: 'Low: 7.4%',
    footLabel: 'Owner',
    footValue: 'Vendor',
  },
]

export const alerts = [
  {
    id: 1,
    severity: 'high',
    title: 'ALERT 01: OTA below SLA',
    scopeLabel: 'Scope',
    scope: 'All vendors',
    metrics: [
      {
        label: 'Current vs Baseline',
        big: '93.0%',
        bigTone: 'error',
        small: '/ 95.0% baseline',
        note: '\u0394 \u22122.0pp deficit',
        noteTone: 'error',
      },
      {
        label: 'Operational Impact',
        big: '12,000',
        small: 'trips affected',
        note: '142 morning staging routes',
      },
      {
        label: 'Primary Contribution',
        big: 'Vendor X',
        bigTone: 'error',
        note: '42% of delay gap',
        noteTone: 'title',
      },
      {
        label: 'Trigger Benchmark',
        big: 'vs SLA & prior cycle',
        bigSmall: true,
        note: 'Breached at 06:12 IST',
      },
    ],
    reasoning:
      'OTA declined 2pp this cycle and is now below the 95% SLA. Vendor X contributes 42% of the gap, making it the highest-impact operational driver. Heavy bottlenecking observed on Outer Ring Road corridors between 07:30 and 08:45 IST.',
    recommended:
      'Re-route high-risk routes, add buffer, and review vendor penalty.',
    owner: 'Vendor',
    hasCopyForVendor: true,
    vendorName: 'Vendor X',
    vendorOta: '91.2%',
    actionLabel: 'Approve action',
    breakdown: {
      confidence: '98.4%',
      rows: [
        ['What Happened:', 'OTA SLA breach'],
        ['Current Value:', '93.0%'],
        ['SLA / Benchmark:', '95.0%'],
        ['Previous Cycle:', '95.0%'],
        ['Peer Comparison:', '96.2%'],
        ['Affected Trips:', '12,000 trips'],
        ['Contribution Share:', 'Vendor X 42%'],
        ['Owner / Execution:', 'Vendor Desk'],
      ],
      note: 'Telemetry confirms 8 distinct bottleneck chokepoints along Outer Ring Road cloverleaf. Re-route 142 morning staging cabs with an extra 15-minute dispatch slotting buffer.',
    },
  },
  {
    id: 2,
    severity: 'high',
    title: 'ALERT 02: Sev-1 alert spike',
    scopeLabel: 'Scope',
    scope: 'Central Dispatch / Night Cabs',
    metrics: [
      {
        label: 'Open / Unacknowledged',
        big: '18',
        bigTone: 'error',
        inlineNote: '(7 unacknowledged)',
        inlineNoteId: 'card2-unack-text',
        note: 'Oldest: 47 min awaiting dispatcher',
      },
      {
        label: 'Benchmark Threshold',
        big: '30 min SLA',
        note: '17 min past breach limit',
        noteTone: 'error',
      },
      {
        label: 'Incident Category',
        big: 'Unscheduled Stop & SOS Beacon',
        bigSmall: true,
        note: '3 Female solo late-shift cabs',
      },
      {
        label: 'Escalation Status',
        big: 'Tier 2 Ops',
        bigTone: 'warning',
        note: 'On-call lead paged',
        id: 'alert2-status',
      },
    ],
    reasoning:
      'Seven Sev-1 incidents remain unacknowledged beyond the operational SLA of 30 minutes. Telemetry indicates cabs stopped in non-geofenced areas with panic button telematics triggered in 2 vehicles. Requires immediate manual verification.',
    recommended: 'Acknowledge open Sev-1s and run escort audit.',
    owner: 'Ops',
    ownerTone: 'error',
    hasReviewAlerts: true,
    hasAckButton: true,
    breakdownSimple: [
      ['Ack SLA:', '30 min max'],
      ['Mean Ack Time:', '12.4 min'],
      ['Queue Delay:', '+34.6 min'],
      ['Escort Status:', '4 unverified'],
    ],
  },
  {
    id: 3,
    severity: 'medium',
    title: 'ALERT 03: Cost outlier detected',
    scopeLabel: 'Vendor',
    scope: 'Vendor Y',
    metrics: [
      {
        label: 'Cost / Trip',
        big: '\u20B91,982',
        small: '/ trip',
        note: 'Peer baseline \u20B91,236',
        noteTone: 'warning',
      },
      {
        label: 'Statistical Variance',
        big: '+3.2\u03C3 Outlier',
        bigTone: 'error',
        note: 'High standard deviation',
      },
      {
        label: 'Sanity Threshold',
        big: '>\u20B916k Sanity Flag',
        bigTone: 'error',
        bigSmall: true,
        note: '14 extreme billing lines',
      },
      {
        label: 'Financial Risk',
        big: '\u20B93,42,000',
        note: 'Unapproved billing delta',
      },
    ],
    reasoning:
      "Cost is materially above the peer benchmark and exceeds the expected distribution. Billing logs contain multiple trips billed under 'Special Event' tariff without authorization codes.",
    recommended: 'Hold bill line and verify km slab.',
    owner: 'Ops',
    actionLabel: 'Review cost',
    actionTitle: 'Hold Vendor Y bill line',
    breakdownSimple: [
      ['Median Cost / Trip:', '\u20B91,210'],
      ['Standard Dev:', '\u20B9233'],
      ['Vendor Y Avg:', '\u20B91,982'],
      ['Unslabbed Bills:', '28 records'],
    ],
  },
  {
    id: 4,
    severity: 'medium',
    title: 'ALERT 04: No-show spike',
    scopeLabel: 'Office',
    scope: 'Office B (Tech Hub)',
    metrics: [
      {
        label: 'Current No-Show',
        big: '4.1%',
        bigTone: 'warning',
        small: 'of roster',
        note: '\u0394 +1.8pp vs Peer (2.3%)',
        noteTone: 'warning',
      },
      {
        label: 'Concentration',
        big: 'Evening Shift (21:00)',
        bigSmall: true,
        note: 'Product Eng & QA units',
      },
      {
        label: 'Dead Mileage Incurred',
        big: '648 km',
        note: 'Driver idle wait time: 14.2 min avg',
      },
    ],
    reasoning:
      'No-shows surged at Office B specifically on evening departures following work-from-home policy transition. Standby cabs were held on meter awaiting passengers who opted out without app cancellation.',
    recommended: 'Send shift reminder and arrange standby cab.',
    owner: 'Office',
    actionLabel: 'Review office',
    actionTitle: 'Add standby capacity Office B',
    badgeId: 'act-3-badge',
    breakdownSimple: [
      ['Corporate Baseline:', '2.3%'],
      ['Office A:', '2.1%'],
      ['Office B:', '4.1%'],
      ['Unclaimed Seats:', '84 seats'],
    ],
  },
  {
    id: 5,
    severity: 'low',
    title: 'ALERT 05: CSAT low-rating cluster',
    scopeLabel: 'Cluster',
    scope: 'Route 42 / Driver group Delta',
    metrics: [
      {
        label: 'Cluster CSAT',
        big: '2.8',
        small: '/ 5.0 (Global 4.82)',
        note: '11 low ratings in 48h',
        noteTone: 'error',
      },
      {
        label: 'Cluster Density',
        big: '11 ratings <3\u2605',
        bigSmall: true,
        note: 'Threshold limit: <3',
      },
      {
        label: 'Dominant Feedback Tag',
        big: 'AC Non-functional / Rude',
        bigSmall: true,
        note: '4 designated hatchbacks',
      },
    ],
    reasoning:
      'Route 42 has collected 11 negative ratings this week. All feedback originates from 4 shared cabs assigned to sub-vendor FleetOps. General rider CSAT remains healthy at 4.82 across other corridors.',
    recommended: 'Review driver/cab performance with vendor.',
    owner: 'Vendor',
    actionLabel: 'Inspect cluster',
    actionTitle: 'Inspect CSAT Cluster',
    breakdownSimple: [
      ['Global Excl 0\u2605:', '4.82'],
      ['Route 42 Vol:', '132 trips'],
      ['Specific Drivers:', '4 identified'],
      ['0-star Excluded:', 'Yes'],
    ],
  },
]

export const recommendedActions = [
  {
    id: 'act-1',
    owner: 'Vendor',
    ownerTone: 'secondary',
    title: 'Review Vendor X penalty',
    reason: 'Reason: OTA breach (93.0% vs 95.0% SLA). 42% gap accountability.',
    hasCopy: true,
    vendorName: 'Vendor X',
    vendorOta: '91.2%',
  },
  {
    id: 'act-2',
    owner: 'Ops',
    ownerTone: 'error',
    title: 'Acknowledge open Sev-1 alerts',
    reason: 'Reason: 7 critical incidents beyond 30 min ack SLA.',
    hasReview: true,
    isSev1: true,
  },
  {
    id: 'act-3',
    owner: 'Office B',
    ownerTone: 'secondary',
    title: 'Add standby capacity for Office B',
    reason: 'Reason: No-show spike (4.1%) & driver un-allocation.',
  },
]

export const initialIncidents = [
  {
    id: 'inc-8821',
    code: 'INC-8821',
    waiting: '47 min waiting',
    desc: 'Unscheduled Stop & SOS beacon \u2022 Female solo late-shift cab (Outer Ring Rd)',
    acked: false,
  },
  {
    id: 'inc-8817',
    code: 'INC-8817',
    waiting: '36 min waiting',
    desc: 'Panic Beacon Triggered \u2022 Geofence departure with female rider',
    acked: false,
  },
  {
    id: 'inc-8804',
    code: 'INC-8804',
    waiting: '28 min elapsed',
    desc: 'Route Deviation >4km \u2022 Security verified phone contact with driver',
    acked: true,
  },
]

export const suggestionPills = [
  'Why did OTA drop?',
  'Which routes are affected?',
  'Show open Sev-1 alerts',
  'Which vendors have cost outliers?',
  'Which office has highest no-shows?',
  "Tell me tomorrow's weather",
]
